### ISSUE TITLE
NBA - Wins Losses Games Played, etc.

### ISSUE THREAD

**Issue by cfox570** [davidjkrause/sportsipy#5]
**Is your feature request related to a problem? Please describe.**
I am looking for WINS LOSES GAMES PLAYED that are missing from NBA stats but present in NFL, MLB, NCAAB.

**Describe the solution you'd like**

Add these elements to constants and other files as appropriate.
'games_played': 'td[data-stat="g"]:first',
'wins': 'td[data-stat="wins"]:first',
'losses': 'td[data-stat="losses"]:first',
'win_percentage': 'td[data-stat="win_loss_pct"]:first',

**Describe alternatives you've considered**
Retrieving the data from games will require too many web requests.

**Additional context**

**Comment by davidjkrause** [comment]
Please try out the updated master branch, the missing requested fields were added and tested.

**Comment by cfox570** [comment]
Wow!  Works great.  Thanks for the quick update.

On Dec 28, 2023, at 1:44 PM, David Krause ***@***.***> wrote:


Please try out the updated master branch, the missing requested fields were added and tested.
